[versions]
jvmTarget = "17"
junit = "6.1.0"
owaspDepdencyCheck = "13.0.0"
licenseReport = "3.1.4"

[libraries]
dependencyCheck = { module = "org.owasp:dependency-check-gradle", version.ref = "owaspDepdencyCheck" }
licenseReport = { module = "com.github.jk1.dependency-license-report:com.github.jk1.dependency-license-report.gradle.plugin", version.ref = "licenseReport" }
kotlinxDatetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.8.0"
kotlinxSerialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0"

databaseDrivers-postgres = "org.postgresql:postgresql:42.7.11"
databaseDrivers-mssql = "com.microsoft.sqlserver:mssql-jdbc:12.2.0.jre11"

test-junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
test-junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
test-junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }
test-junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
pluginPublish = "com.gradle.plugin-publish:2.1.1"
spotless = "com.diffplug.spotless:8.5.1"
